CREATE TABLE ASSESSOR_PROPERTY_MAPPING AS
SELECT
    MLS_IDS[0]::STRING AS MLS_ID,           -- Gets first element as string
    ASSESSOR_IDS[0]::STRING AS ASSESSOR_ID  -- Gets first element as string
FROM ROC_ANALYTICS.ANALYTICS.ADDRESSES_MASTER
GROUP BY
MLS_ID,
ASSESSOR_ID
ORDER BY ASSESSOR_ID;