CREATE TABLE ASSESSOR_PROPERTY_MAPPING AS
SELECT
    f.value::STRING AS MLS_ID,
    a.value::STRING AS ASSESSOR_ID
FROM ROC_ANALYTICS.ANALYTICS.ADDRESSES_MASTER,
LATERAL FLATTEN(input => MLS_IDS) f,
LATERAL FLATTEN(input => ASSESSOR_IDS) a
GROUP BY MLS_ID, ASSESSOR_ID
ORDER BY ASSESSOR_ID;